# отключает наследование Connection: keep-alive и избегает проблем с HTTP/1.0.
proxy_http_version 1.1;
proxy_set_header Connection "";

# Стандартные заголовки для передачи данных клиента
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Port $server_port;

# Проброс Cookies для сессий
proxy_set_header Cookie $http_cookie;
