"""add param index in fields lat and lon

Revision ID: 945e55648dcc
Revises: 1fb79aa617ac
Create Date: 2026-05-01 00:56:11.646589

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "945e55648dcc"
down_revision: Union[str, Sequence[str], None] = "1fb79aa617ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_ip_caches_lat"), "ip_caches", ["lat"], unique=False)
    op.create_index(op.f("ix_ip_caches_lon"), "ip_caches", ["lon"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ip_caches_lon"), table_name="ip_caches")
    op.drop_index(op.f("ix_ip_caches_lat"), table_name="ip_caches")
    # ### end Alembic commands ###
