"""create tables IPCache and UserRequest

Revision ID: 1fb79aa617ac
Revises:
Create Date: 2026-04-30 16:32:10.689408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fb79aa617ac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ip_caches",
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("zip", sa.String(length=50), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("isp", sa.String(length=100), nullable=False),
        sa.Column("raw_data", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ip", name=op.f("pk_ip_caches")),
    )
    op.create_index(op.f("ix_ip_caches_ip"), "ip_caches", ["ip"], unique=False)
    op.create_table(
        "user_requests",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("ip_queried", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("map_file_path", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ip_queried"], ["ip_caches.ip"], name=op.f("fk_user_requests_ip_queried_ip_caches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_requests")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_requests")
    op.drop_index(op.f("ix_ip_caches_ip"), table_name="ip_caches")
    op.drop_table("ip_caches")
    # ### end Alembic commands ###
